### ISSUE TITLE
Create Commands Skeleton

### ISSUE THREAD

**Issue by Adron** [ThrashingCode/colligere#7]
I've been pondering what the CLI would need. Here's a first draft.

1. `colligere` is the root command.
2. `colligere config set` or something like this to set configuration values.
3. `colligere config view` would be used to pass a parameter to view the particular configuration parameter value.
4. `colligere deluge` is what I'm aiming for.

I'll add additional and add notes here about which I add and for what.

**Comment by jinglish** [comment]
What's the default behavior for `colligere` going to be--display a list of subcommands and their descriptions, a la `kubectl`?

`colligere --version` is a must too.

**Comment by Adron** [comment]
Haha yes, we'll definitely have a --version.  Maybe just a `version`?

**Comment by Adron** [comment]
Me too, and honestly I don't actually know what the defacto should or ought to be. Maybe we should get a metaphysical idealism book on CLI! ;-)

**Comment by Adron** [comment]
Added.
